### ISSUE TITLE
demo_generator.py is referenced in README but not included in the repo

### ISSUE THREAD

**Issue by dHannasch** [raulcostajunior/py_libsudoku#1]
This is very cool!

One note: https://github.com/raulcostajunior/py_libsudoku/commit/b40cfc55fdd7b517db765898a904db0e95c4d6b3 adds a reference to demo_generator.py, which (unlike the very helpful demo_board.py and demo_solver.py) is not in the repo.

**Comment by raulcostajunior** [comment]
Hi,

Glad that you liked!

Thanks for pointing that out. I'll add it to the repo as soon as I can get
the async methods running properly.

Regards,
Raul.

**Comment by raulcostajunior** [comment]
Demo file for Generator added. Extension published to PyPi.
